#!/bin/sh

if [ -z "${MESQUIDA_HOME}" ]
then
  echo "MESQUIDA_HOME is unset" 1>&2
  exit 1
fi

exec /usr/bin/env java \
-p "${MESQUIDA_HOME}/lib" \
-m com.io7m.mesquida.main/com.io7m.mesquida.Main \
"$@"
